"""
GitHub Commit → Social Post Agent

Main orchestrator that runs the full pipeline:
  1. Scan recent commits for lesson-worthy content
  2. Score and filter commits
  3. Generate LinkedIn-first posts (with X thread + IG caption)
  4. Store each post as a GitHub Issue
  5. Request analytics for published posts
  6. Update learning state from collected analytics
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Optional

from .analytics import (
    LearningState,
    _apply_qualitative_feedback,
    infer_implicit_feedback,
    fetch_issue_analytics,
    fetch_issue_feedback,
    get_analytics_prompt,
    get_best_hook_pattern,
    should_apply_feedback,
    update_learning_state,
)
from .commit_scanner import scan_all_user_commits, scan_commits, scan_repos
from .experiments import ExperimentManager, EXPERIMENT_PLAN
from .github_storage import (
    add_analytics_comment,
    create_post_issue,
    get_analytics_request_message,
    load_posts_from_issues,
    update_issue_status,
)
from .models import Post, PostFeedback, PostStatus
from .post_generator import (
    HOOK_PATTERNS,
    QUALITY_GATE_DEFAULT_MAX_REWRITES,
    QUALITY_GATE_DEFAULT_THRESHOLD,
    generate_post_with_quality_gate,
)
from .screenshot_learning import (
    DEFAULT_SCREENSHOT_STATE_PATH,
    ScreenshotLearningState,
    build_signal_balance,
    run_screenshot_learning_cycle,
)
from .regeneration import (
    apply_generic_feedback,
    apply_similar_feedback,
    classify_feedback,
    handle_abandon,
    regenerate_from_feedback,
    should_regenerate,
)
from .scoring import SCORE_THRESHOLD
from .self_improvement import run_self_improvement_cycle

logger = logging.getLogger(__name__)

# Default paths for persistent state files
DEFAULT_LEARNING_STATE_PATH = "learning_state.json"
DEFAULT_EXPERIMENTS_PATH = "experiments.json"

# How many days back to scan for commits when no 'since' date is provided
DEFAULT_SCAN_DAYS = 7

# Learning-state key used when a large historical issue batch is explicitly
# marked as "bad practice" and should tighten future selection.
HISTORICAL_BAD_BATCH_REASON_PREFIX = "historical_batch_bad_practice_pre_"
DEFAULT_MAX_OPEN_UNPUBLISHED = 10
DEFAULT_MAX_STALE_UNPUBLISHED = 4
DEFAULT_STALE_DAYS = 7
README_METRICS_START = "<!-- METRICS_DASHBOARD_START -->"
README_METRICS_END = "<!-- METRICS_DASHBOARD_END -->"


@dataclass
class BacklogStats:
    """Backlog health summary for open social-post issues."""

    total_open_social: int = 0
    open_unpublished: int = 0
    stale_unpublished: int = 0


@dataclass
class CommitDecision:
    """OpenAI decision for whether a commit should become a post."""

    accept: bool
    reason: str
    confidence: float = 0.0


def _issue_status_from_labels(labels: list[dict]) -> Optional[str]:
    """Return the issue status from status:* labels."""
    for label in labels:
        name = label.get("name", "")
        if name.startswith("status:"):
            return name.split(":", 1)[1]
    return None


def _parse_iso_datetime(value: str) -> Optional[datetime]:
    """Parse ISO timestamp into timezone-aware datetime."""
    if not value:
        return None
    try:
        dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt
    except ValueError:
        return None


def _demote_markdown_headings(markdown: str, levels: int = 1) -> str:
    """Demote markdown heading levels so dashboard can be embedded in README."""
    in_fence = False
    lines = []
    for line in markdown.splitlines():
        if line.strip().startswith("```"):
            in_fence = not in_fence
            lines.append(line)
            continue
        if (not in_fence) and line.startswith("#"):
            hash_count = len(line) - len(line.lstrip("#"))
            if hash_count > 0 and line[hash_count:hash_count + 1] == " ":
                new_hashes = "#" * min(6, hash_count + levels)
                line = f"{new_hashes}{line[hash_count:]}"
        lines.append(line)
    return "\n".join(lines)


def build_readme_metrics_block(metrics_markdown: str) -> str:
    """Return the auto-generated metrics block for README embedding."""
    demoted = _demote_markdown_headings(metrics_markdown, levels=1).strip()
    return (
        f"{README_METRICS_START}\n"
        "<!-- Auto-generated by `python -m src.agent metrics` -->\n\n"
        f"{demoted}\n"
        f"{README_METRICS_END}"
    )


def update_readme_metrics_section(readme_path: str, metrics_markdown: str) -> bool:
    """
    Update README metrics section between marker comments.

    Returns True when section markers were found and handled, else False.
    """
    path = Path(readme_path)
    if not path.exists():
        return False
    content = path.read_text(encoding="utf-8")
    start = content.find(README_METRICS_START)
    end = content.find(README_METRICS_END)
    if start == -1 or end == -1 or end < start:
        return False

    end += len(README_METRICS_END)
    replacement = build_readme_metrics_block(metrics_markdown)
    new_content = content[:start] + replacement + content[end:]
    path.write_text(new_content, encoding="utf-8")
    return True


def fetch_social_post_backlog(
    repo: str,
    token: str,
    stale_days: int = DEFAULT_STALE_DAYS,
) -> BacklogStats:
    """
    Fetch open social-post issues and compute backlog health stats.

    Unpublished backlog includes `status:draft` and `status:approved`.
    Stale backlog includes unpublished issues older than `stale_days`.
    """
    import requests as _requests  # noqa: PLC0415

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    stats = BacklogStats()
    now = datetime.now(timezone.utc)
    cutoff = now - timedelta(days=stale_days)

    page = 1
    while True:
        url = f"https://api.github.com/repos/{repo}/issues"
        resp = _requests.get(
            url,
            headers=headers,
            params={"state": "open", "labels": "social-post", "per_page": 100, "page": page},
            timeout=30,
        )
        resp.raise_for_status()
        batch = resp.json()
        if not batch:
            break

        for issue in batch:
            if "pull_request" in issue:
                continue
            stats.total_open_social += 1
            status = _issue_status_from_labels(issue.get("labels", [])) or "draft"
            if status not in (PostStatus.DRAFT.value, PostStatus.APPROVED.value):
                continue

            stats.open_unpublished += 1
            created_at = _parse_iso_datetime(issue.get("created_at", ""))
            if created_at is not None and created_at <= cutoff:
                stats.stale_unpublished += 1

        if len(batch) < 100:
            break
        page += 1

    return stats


# Days without feedback before auto-archiving stale drafts during scan
AUTO_ARCHIVE_STALE_DAYS = 14


def auto_archive_stale_issues(
    repo: str,
    token: str,
    stale_days: int = AUTO_ARCHIVE_STALE_DAYS,
) -> int:
    """
    Close stale unpublished draft issues that have had no feedback.

    Returns the number of issues archived.
    """
    import requests as _requests  # noqa: PLC0415

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    now = datetime.now(timezone.utc)
    cutoff = now - timedelta(days=stale_days)
    archived_count = 0

    page = 1
    while True:
        url = f"https://api.github.com/repos/{repo}/issues"
        resp = _requests.get(
            url,
            headers=headers,
            params={"state": "open", "labels": "social-post", "per_page": 100, "page": page},
            timeout=30,
        )
        resp.raise_for_status()
        batch = resp.json()
        if not batch:
            break

        for issue in batch:
            if "pull_request" in issue:
                continue
            status = _issue_status_from_labels(issue.get("labels", [])) or "draft"
            if status not in (PostStatus.DRAFT.value, PostStatus.APPROVED.value):
                continue
            created_at = _parse_iso_datetime(issue.get("created_at", ""))
            if created_at is None or created_at > cutoff:
                continue

            issue_number = issue["number"]
            title = issue.get("title", "")
            # Close the issue and add an explanatory comment
            comment_url = f"https://api.github.com/repos/{repo}/issues/{issue_number}/comments"
            _requests.post(
                comment_url,
                headers=headers,
                json={"body": (
                    f"Auto-archived: this draft was open for {stale_days}+ days with no "
                    "publish action. Closing to unblock new post generation. "
                    "Reopen if you'd like to revisit this draft."
                )},
                timeout=30,
            )
            # Close the issue
            close_url = f"https://api.github.com/repos/{repo}/issues/{issue_number}"
            _requests.patch(
                close_url,
                headers=headers,
                json={"state": "closed"},
                timeout=30,
            )
            # Add auto-archived label
            label_url = f"https://api.github.com/repos/{repo}/issues/{issue_number}/labels"
            _requests.post(
                label_url,
                headers=headers,
                json={"labels": ["auto-archived"]},
                timeout=30,
            )
            archived_count += 1
            logger.info("Auto-archived stale issue #%d: %s", issue_number, title)

        if len(batch) < 100:
            break
        page += 1

    if archived_count:
        print(f"Auto-archived {archived_count} stale draft(s) older than {stale_days} days.")
    return archived_count


def _get_openai_client():
    """Return an openai.OpenAI client if the API key is set, else None."""
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        logger.warning("OPENAI_API_KEY not set — posts will use placeholder content")
        return None
    try:
        import openai  # noqa: PLC0415
        return openai.OpenAI(api_key=api_key)
    except ImportError:
        logger.warning("openai package not installed — posts will use placeholder content")
        return None


def _parse_bad_batch_date(reason: str) -> Optional[datetime]:
    """Extract date from a bad-batch reason key like '..._pre_2026-03-03_...'."""
    import re
    match = re.search(r"_pre_(\d{4}-\d{2}-\d{2})", reason)
    if match:
        try:
            return datetime.strptime(match.group(1), "%Y-%m-%d").replace(tzinfo=timezone.utc)
        except ValueError:
            pass
    return None


def _decay_factor(age_days: float) -> float:
    """Return a decay multiplier based on age in days.

    0-30 days: full weight (1.0)
    30-60 days: half weight (0.5)
    60-90 days: quarter weight (0.25)
    90+ days: ignored (0.0)
    """
    if age_days < 30:
        return 1.0
    if age_days < 60:
        return 0.5
    if age_days < 90:
        return 0.25
    return 0.0


def apply_learning_guardrails(
    learning_state: LearningState,
    threshold: float,
    max_posts: int,
) -> tuple[float, int]:
    """
    Tighten scan settings when historical bad-practice signals are present.

    If the learning state contains a strong historical bad-batch signal, we:
    - increase minimum commit threshold (quality-first)
    - reduce post volume per run (avoid flooding with weak drafts)

    Signals decay over time so the system can recover from historical issues.
    Also checks archived_not_published_reasons with decay applied.
    """
    now = datetime.now(timezone.utc)
    bad_batch_count = 0.0

    # Check both active and archived reasons for bad-batch signals (with decay)
    for source in [
        learning_state.not_published_reasons or {},
        learning_state.archived_not_published_reasons or {},
    ]:
        for reason, count in source.items():
            if reason.lower().startswith(HISTORICAL_BAD_BATCH_REASON_PREFIX):
                batch_date = _parse_bad_batch_date(reason)
                if batch_date:
                    age_days = (now - batch_date).total_seconds() / 86400
                    bad_batch_count += int(count) * _decay_factor(age_days)
                else:
                    bad_batch_count += int(count)

    adjusted_threshold = threshold
    adjusted_max_posts = max_posts

    if bad_batch_count >= 10:
        adjusted_threshold = max(adjusted_threshold, 40.0)
        adjusted_max_posts = min(adjusted_max_posts, 3)
        logger.info(
            "Learning guardrail active from historical bad-practice batch "
            "(effective_count=%.1f): threshold %.1f -> %.1f, max_posts %d -> %d",
            bad_batch_count,
            threshold,
            adjusted_threshold,
            max_posts,
            adjusted_max_posts,
        )
    elif bad_batch_count > 0:
        logger.info(
            "Historical bad-practice batch decayed below threshold "
            "(effective_count=%.1f < 10). No guardrail applied.",
            bad_batch_count,
        )

    return adjusted_threshold, adjusted_max_posts


# Implicit/automated reason keys that should not be fed into the editorial gate prompt.
_IMPLICIT_REASON_KEYS = {"no_feedback_72h", "stale_unpublished_7d"}


def _historical_bad_practice_summary(learning_state: LearningState, top_n: int = 3) -> str:
    """Return a compact summary of explicit negative reasons for the editorial gate.

    Excludes implicit/automated signals (no_feedback_72h, stale_unpublished_7d) which
    reflect user inaction, not content quality. Caps to top_n reasons with count >= 3
    to avoid overwhelming the prompt.
    """
    reasons = learning_state.not_published_reasons or {}
    # Filter to explicit user feedback only, with meaningful count
    explicit = {
        reason: int(count)
        for reason, count in reasons.items()
        if reason not in _IMPLICIT_REASON_KEYS and int(count) >= 3
    }
    if not explicit:
        return "No significant content quality issues recorded."
    ranked = sorted(explicit.items(), key=lambda kv: -kv[1])[:top_n]
    return "; ".join(f"{reason} ({count}x)" for reason, count in ranked)


def decide_commit_with_openai(openai_client, source, learning_state: LearningState, model: str = "gpt-5.4-mini") -> CommitDecision:
    """
    Ask OpenAI whether this commit should become a social post.

    The model is used as a qualitative gate to avoid repeating low-value,
    internal-only patterns that previously failed to get published.
    """
    if openai_client is None:
        return CommitDecision(accept=True, reason="OpenAI unavailable; default accept.", confidence=0.0)

    history_summary = _historical_bad_practice_summary(learning_state)
    system_prompt = (
        "You are an editorial gatekeeper for technical LinkedIn posts. "
        "Decide if a commit should become a post. Reject repetitive internal maintenance "
        "or meta tooling churn. Accept only if an external engineering audience will learn "
        "a concrete, useful lesson. "
        "NICHE REQUIREMENT: Posts must relate to AI agents, Temporal.io, distributed systems, "
        "or LLMs (Claude, GPT, Gemini). Reject commits outside this niche. "
        "Respond ONLY valid JSON."
    )
    user_prompt = (
        "Past content themes that underperformed (use as guidance, not hard blocks):\n"
        f"{history_summary}\n\n"
        "Commit candidate:\n"
        f"- message: {source.message}\n"
        f"- files_changed: {', '.join(source.files_changed[:8])}\n"
        f"- diff_summary: {source.diff_summary}\n"
        f"- score: {source.score:.1f}\n\n"
        "Return JSON with keys:\n"
        '{"decision":"accept|reject","reason":"short reason","confidence":0.0}'
    )
    try:
        response = openai_client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.0,
            max_completion_tokens=220,
        )
        content = (response.choices[0].message.content or "").strip()
    except Exception as exc:  # noqa: BLE001
        logger.warning("OpenAI commit decision failed for %s: %s", source.sha[:8], exc)
        return CommitDecision(accept=True, reason="OpenAI decision failed; default accept.", confidence=0.0)

    try:
        payload = json.loads(content)
    except json.JSONDecodeError:
        start = content.find("{")
        end = content.rfind("}")
        if start != -1 and end != -1 and end > start:
            try:
                payload = json.loads(content[start : end + 1])
            except json.JSONDecodeError:
                payload = {}
        else:
            payload = {}

    decision_raw = str(payload.get("decision", "accept")).strip().lower()
    accept = decision_raw == "accept"
    reason = str(payload.get("reason", "")).strip() or "No reason provided."
    try:
        confidence = float(payload.get("confidence", 0.0))
    except (TypeError, ValueError):
        confidence = 0.0

    return CommitDecision(accept=accept, reason=reason, confidence=confidence)


def run_scan(
    repo: Optional[str] = None,
    token: str = "",
    since: Optional[str] = None,
    branch: str = "main",
    max_posts: int = 10,
    learning_state_path: str = DEFAULT_LEARNING_STATE_PATH,
    experiments_path: str = DEFAULT_EXPERIMENTS_PATH,
    dry_run: bool = False,
    username: Optional[str] = None,
    repos: Optional[list[str]] = None,
    issue_repo: Optional[str] = None,
    threshold: float = SCORE_THRESHOLD,
    backlog_throttle_enabled: bool = False,
    max_open_unpublished: int = DEFAULT_MAX_OPEN_UNPUBLISHED,
    max_stale_unpublished: int = DEFAULT_MAX_STALE_UNPUBLISHED,
    stale_days: int = DEFAULT_STALE_DAYS,
    quality_threshold: float = QUALITY_GATE_DEFAULT_THRESHOLD,
    max_rewrites: int = QUALITY_GATE_DEFAULT_MAX_REWRITES,
    variations_per_commit: int = 1,
) -> list[Post]:
    """
    Run a full commit scan → post generation → GitHub Issue creation cycle.

    Args:
        repo:                 Full repo name (owner/repo).  Mutually exclusive with username/repos.
        token:                GitHub token with repo + issues write access.
        since:                ISO 8601 date string; only scan commits after this.
        branch:               Branch to scan.
        max_posts:            Maximum posts to generate per run.
        learning_state_path:  Path to the learning state JSON file.
        experiments_path:     Path to the experiments JSON file.
        dry_run:              If True, print posts but don't create issues.
        username:             GitHub username — scan ALL repos for this user.
        repos:                Explicit list of repos to scan (e.g. from config.yaml source_repos).
        issue_repo:           Repo where social-post Issues are created (defaults to repo if single).
        threshold:            Minimum commit score to qualify for post generation.
        backlog_throttle_enabled:
                              If True, pause generation when draft backlog is too high.
        max_open_unpublished: Maximum allowed open unpublished social-post issues.
        max_stale_unpublished:
                              Maximum allowed stale unpublished issues before pausing.
        stale_days:           Age threshold (days) for stale unpublished issues.
        quality_threshold:    Minimum LinkedIn post quality score required (0-100).
        max_rewrites:         Maximum OpenAI rewrite attempts when quality is low.

    Returns:
        List of generated Post objects.
    """
    if not repo and not username and not repos:
        raise ValueError("Either 'repo', 'username', or 'repos' must be provided.")
    if since is None:
        cutoff = datetime.now(timezone.utc) - timedelta(days=DEFAULT_SCAN_DAYS)
        since = cutoff.isoformat()

    logger.info("Starting commit scan (since=%s)", since)

    # Resolve issue_repo: where social-post Issues are created.
    # Falls back to repo (single-repo mode) or the first source repo.
    if issue_repo is None:
        issue_repo = repo or (repos[0] if repos else None)

    # Auto-archive very stale drafts (14+ days) to prevent permanent backlog deadlock.
    if backlog_throttle_enabled and not dry_run and issue_repo:
        try:
            auto_archive_stale_issues(issue_repo, token, stale_days=AUTO_ARCHIVE_STALE_DAYS)
        except Exception as exc:  # noqa: BLE001
            logger.warning("Auto-archive failed (non-fatal): %s", exc)

    # Backlog throttle: pause generation when too many unpublished drafts accumulate.
    if backlog_throttle_enabled and not dry_run and issue_repo:
        backlog = fetch_social_post_backlog(issue_repo, token, stale_days=stale_days)
        if (
            backlog.open_unpublished >= max_open_unpublished
            or backlog.stale_unpublished >= max_stale_unpublished
        ):
            logger.warning(
                "Backlog throttle activated for %s: open_unpublished=%d (limit=%d), "
                "stale_unpublished=%d (limit=%d).",
                repo,
                backlog.open_unpublished,
                max_open_unpublished,
                backlog.stale_unpublished,
                max_stale_unpublished,
            )
            print(
                "⏸ Backlog throttle activated — skipping new draft generation.\n"
                f"Open unpublished: {backlog.open_unpublished} (limit {max_open_unpublished})\n"
                f"Stale unpublished (>{stale_days}d): {backlog.stale_unpublished} "
                f"(limit {max_stale_unpublished})"
            )
            return []

    # Load persistent state
    learning_state = LearningState.load(learning_state_path)
    experiments = ExperimentManager(experiments_path)

    # Apply guardrails learned from prior rejected batches.
    threshold, max_posts = apply_learning_guardrails(learning_state, threshold, max_posts)

    # Get or start an experiment
    active_exp = experiments.get_active_experiment()
    if active_exp is None:
        active_exp = experiments.start_next_experiment()

    # Pick the best hook pattern from learning state
    best_hook = get_best_hook_pattern(learning_state)

    # Scan commits — explicit repo list, single repo, or all repos for a user
    if repos:
        logger.info("Scanning explicit repo list: %s", repos)
        source_commits = scan_repos(
            repos, token, since=since, branch=branch, threshold=threshold
        )
    elif username:
        logger.info("Scanning all repositories for user %s", username)
        source_commits = scan_all_user_commits(
            username, token, since=since, branch=branch, threshold=threshold
        )
    else:
        logger.info("Scanning commits for %s (branch=%s)", repo, branch)
        source_commits = scan_commits(
            repo, token, since=since, branch=branch, threshold=threshold  # type: ignore[arg-type]
        )
    if not source_commits:
        logger.info("No lesson-worthy commits found.")
        return []

    # Generate posts
    openai_client = _get_openai_client()
    if openai_client is None and not dry_run:
        raise RuntimeError(
            "OPENAI_API_KEY is required for non-dry-run scans. "
            "Refusing to create low-quality placeholder issues."
        )
    if openai_client is not None:
        filtered_commits = []
        for source in source_commits:
            decision = decide_commit_with_openai(openai_client, source, learning_state)
            if decision.accept:
                filtered_commits.append(source)
            else:
                logger.info(
                    "OpenAI rejected commit %s for posting (confidence=%.2f): %s",
                    source.sha[:8],
                    decision.confidence,
                    decision.reason,
                )
        source_commits = filtered_commits
        if not source_commits:
            logger.info("No commits passed OpenAI editorial gate.")
            return []
    generated_posts: list[Post] = []

    # --- Pre-generation agents ---
    # Variety Guardian: recommend hooks, skip off-ICP or repetitive commits
    variety_recommendations: dict[str, dict] = {}
    if openai_client is not None and issue_repo:
        try:
            from .agents.variety_guardian import guard_variety  # noqa: PLC0415
            from .github_storage import load_posts_from_issues  # noqa: PLC0415

            recent_posts_raw = load_posts_from_issues(issue_repo, token, state="open")
            recent_posts = [
                {"hook_pattern": p.hook_pattern, "tags": p.tags, "lesson": p.lesson}
                for p in recent_posts_raw[:10]
            ]
            candidates = [
                {"sha": s.sha, "message": s.message, "repo": s.repo, "tags": s.tags if hasattr(s, "tags") else []}
                for s in source_commits[:max_posts]
            ]
            recs = guard_variety(openai_client, candidates, recent_posts)
            for rec in recs:
                variety_recommendations[rec["sha"]] = rec
            # Filter out skipped commits
            before_count = len(source_commits)
            source_commits = [
                s for s in source_commits
                if not variety_recommendations.get(s.sha, {}).get("skip", False)
            ]
            skipped = before_count - len(source_commits)
            if skipped:
                logger.info("Variety Guardian skipped %d commits (off-ICP or repetitive)", skipped)
        except Exception:  # noqa: BLE001
            logger.warning("Variety Guardian failed (non-fatal)", exc_info=True)

    # Build list of hook patterns for variations
    all_hooks = list(HOOK_PATTERNS.keys())
    num_variations = max(1, variations_per_commit)

    for source in source_commits[:max_posts]:
        # Determine hook patterns for this commit's variations
        variation_hooks: list[tuple[str, Optional[str], Optional[str]]] = []

        # Use variety guardian's recommended hook if available
        guardian_rec = variety_recommendations.get(source.sha, {})
        recommended_hook = guardian_rec.get("hook_pattern", best_hook)

        if active_exp is not None:
            from .models import ExperimentVariable  # noqa: PLC0415
            if active_exp.variable == ExperimentVariable.HOOK_STYLE:
                # During experiments, use experiment-assigned variants
                for _ in range(num_variations):
                    variant = experiments.assign_variant(active_exp)
                    variation_hooks.append((variant, active_exp.id, variant))
            else:
                variation_hooks.append((recommended_hook, None, None))
        else:
            variation_hooks.append((recommended_hook, None, None))

        # Fill remaining variation slots with diverse hook patterns
        if len(variation_hooks) < num_variations:
            import random  # noqa: PLC0415
            remaining_hooks = [h for h in all_hooks if h != best_hook]
            random.shuffle(remaining_hooks)
            for extra_hook in remaining_hooks[:num_variations - len(variation_hooks)]:
                variation_hooks.append((extra_hook, None, None))

        # Code Snippet Curator: fetch best snippet from actual diff
        curated_snippet = None
        if openai_client is not None:
            try:
                from .agents.code_curator import curate_code_snippet  # noqa: PLC0415
                curated_snippet = curate_code_snippet(openai_client, source.sha, source.repo, token)
                if curated_snippet:
                    logger.info("Code curator selected snippet (%s) for %s", curated_snippet.get("language", "?"), source.sha[:8])
            except Exception:  # noqa: BLE001
                logger.warning("Code curator failed (non-fatal)", exc_info=True)

        commit_posts: list[Post] = []
        for var_idx, (hook_pattern, experiment_id, experiment_variant) in enumerate(variation_hooks):
            post = generate_post_with_quality_gate(
                source=source,
                hook_pattern=hook_pattern,
                experiment_id=experiment_id,
                experiment_variant=experiment_variant,
                openai_client=openai_client,
                quality_threshold=quality_threshold,
                max_rewrites=max_rewrites,
                curated_snippet=curated_snippet,
            )
            if post is None:
                logger.info(
                    "Variation %d/%d for commit %s (hook=%s) failed quality gate",
                    var_idx + 1,
                    len(variation_hooks),
                    source.sha[:8],
                    hook_pattern,
                )
                continue

            # Tag the variation number in the post ID to avoid collisions
            if var_idx > 0:
                post.id = f"{post.id}-v{var_idx + 1}"

            # Pre-creation agent quality loop: run agents to improve the post
            # before it becomes a GitHub Issue
            if openai_client is not None:
                try:
                    from .agent_loop import agent_quality_loop  # noqa: PLC0415
                    loop_result = agent_quality_loop(
                        post_text=post.linkedin_post,
                        commit_message=source.message,
                        commit_diff=source.diff_summary,
                        tags=post.tags,
                        hook_pattern=post.hook_pattern,
                        openai_client=openai_client,
                        learning_state=learning_state,
                    )
                    if loop_result.improved:
                        post.linkedin_post = loop_result.post_text
                        logger.info(
                            "Agent loop improved post %s after %d iteration(s)",
                            post.id, loop_result.iterations,
                        )
                except Exception:  # noqa: BLE001
                    logger.warning("Agent quality loop failed (non-fatal)", exc_info=True)

            commit_posts.append(post)

        if not commit_posts:
            logger.info(
                "Skipping commit %s — all %d variations failed quality gate",
                source.sha[:8],
                len(variation_hooks),
            )
            continue

        for post in commit_posts:
            if dry_run:
                print("\n" + "=" * 60)
                print(f"DRY RUN — Post for commit {source.sha[:8]} (hook={post.hook_pattern})")
                print("=" * 60)
                print(post.linkedin_post)
                print("\n--- X Thread ---")
                print(post.x_thread)
                print("\n--- IG Caption ---")
                print(post.ig_caption)
                generated_posts.append(post)
                continue

            # Store as GitHub Issue in the issue_repo (not the source repo)
            issue_number = create_post_issue(
                post, issue_repo, token,  # type: ignore[arg-type]
                openai_client=openai_client,
                source_commit=source,
                learning_state=learning_state,
            )
            post.github_issue_number = issue_number
            generated_posts.append(post)

            logger.info("Created post %s → Issue #%d (hook=%s)", post.id, issue_number, post.hook_pattern)

    return generated_posts


def _load_config_section(section: str) -> dict:
    """Load a section from config.yaml."""
    from pathlib import Path as _Path  # noqa: PLC0415
    config_path = _Path("config.yaml")
    if not config_path.exists():
        return {}
    try:
        import yaml  # noqa: PLC0415
        with config_path.open() as f:
            config = yaml.safe_load(f) or {}
        return config.get(section, {})
    except Exception:  # noqa: BLE001
        return {}


def _auto_save_published_post(post: Post) -> None:
    """Save a published post to good-social-posts/ as a few-shot example."""
    good_posts_dir = Path("good-social-posts")
    good_posts_dir.mkdir(exist_ok=True)
    filename = f"post-{post.github_issue_number or post.id}.md"
    filepath = good_posts_dir / filename
    if filepath.exists():
        return
    filepath.write_text(
        f"# Published Post (auto-saved)\n\n## Final LinkedIn Post\n\n{post.linkedin_post}\n",
        encoding="utf-8",
    )
    logger.info("Auto-saved published post to %s", filepath)


def _load_source_repos() -> list[str]:
    """Load source_repos from config.yaml."""
    return _load_config_section("agent").get("source_repos", [])


def _load_regeneration_config() -> dict:
    """Load regeneration config with defaults."""
    cfg = _load_config_section("regeneration")
    return {
        "enabled": cfg.get("enabled", True),
        "max_attempts": cfg.get("max_attempts", 3),
        "scan_days": cfg.get("scan_days", 14),
        "score_threshold": cfg.get("score_threshold", 20.0),
    }


def run_analytics_collection(
    repo: str,
    token: str,
    posts: list[Post],
    learning_state_path: str = DEFAULT_LEARNING_STATE_PATH,
    experiments_path: str = DEFAULT_EXPERIMENTS_PATH,
) -> None:
    """
    Check for analytics on published posts and update the learning state.

    For each post with a GitHub Issue, this:
    1. Collects qualitative feedback regardless of post status or analytics presence.
       (Rejections are the most important signal — we need to know *why* posts
       weren't published even when no engagement data exists.)
    2. For published posts that have analytics: runs the full quantitative learning loop.
    3. For published posts without analytics yet: prints a prompt asking the user to enter them.
    """
    learning_state = LearningState.load(learning_state_path)
    experiments = ExperimentManager(experiments_path)

    for post in posts:
        if post.github_issue_number is None:
            continue

        # --- Pass 1: collect qualitative feedback for every post ---
        # This runs regardless of status so that rejection reasons from
        # non-published (draft/archived) posts are also captured.
        feedback = fetch_issue_feedback(repo, token, post.github_issue_number, post.id)
        has_explicit_feedback = feedback is not None
        explicit_published = feedback is not None and feedback.published is True
        if feedback is not None and should_apply_feedback(learning_state, post.id, feedback):
            _apply_qualitative_feedback(learning_state, feedback)
            learning_state.save(learning_state_path)

        # Promote to published when quick feedback explicitly says it's published.
        if explicit_published and post.status != PostStatus.PUBLISHED:
            update_issue_status(repo, token, post.github_issue_number, PostStatus.PUBLISHED)
            post.status = PostStatus.PUBLISHED
            # Auto-save to good-social-posts as a few-shot example
            _auto_save_published_post(post)

        # --- Pass 1b: infer feedback from inactivity for non-published posts ---
        implicit_feedback = infer_implicit_feedback(
            state=learning_state,
            post=post,
            has_explicit_feedback=has_explicit_feedback,
            explicit_published=explicit_published,
        )
        for event_key, inferred in implicit_feedback:
            if should_apply_feedback(learning_state, post.id, inferred):
                _apply_qualitative_feedback(learning_state, inferred)
                learning_state.save(learning_state_path)
                logger.info("Applied implicit feedback for %s: %s", post.id, event_key)

        # --- Pass 1c: feedback-driven regeneration ---
        regen_cfg = _load_regeneration_config()
        if (
            regen_cfg["enabled"]
            and has_explicit_feedback
            and feedback is not None
            and post.status not in (PostStatus.PUBLISHED, PostStatus.ABANDONED, PostStatus.ARCHIVED)
        ):
            fb_type = classify_feedback(feedback, post)
            openai_client = _get_openai_client()
            source_repos = _load_source_repos()

            if fb_type == "abandon":
                handle_abandon(post, repo, token)
                post.status = PostStatus.ABANDONED

            elif fb_type == "generic" and source_repos:
                new_posts = apply_generic_feedback(
                    feedback=feedback,
                    feedback_source_issue=post.github_issue_number,
                    open_posts=posts,
                    source_repos=source_repos,
                    issue_repo=repo,
                    token=token,
                    openai_client=openai_client,
                    learning_state=learning_state,
                )
                logger.info("Generic feedback: generated %d replacements", len(new_posts))

            elif fb_type == "post_specific" and source_repos:
                # Check if topic-level rejection applies to siblings
                if feedback.not_published_reason in ("useless_topic", "not_relevant"):
                    new_posts = apply_similar_feedback(
                        feedback=feedback,
                        source_post=post,
                        open_posts=posts,
                        source_repos=source_repos,
                        issue_repo=repo,
                        token=token,
                        openai_client=openai_client,
                        learning_state=learning_state,
                    )
                    logger.info("Similar-topic feedback: closed + replaced %d siblings", len(new_posts))

                if should_regenerate(post):
                    new_post = regenerate_from_feedback(
                        rejected_post=post,
                        feedback=feedback,
                        source_repos=source_repos,
                        issue_repo=repo,
                        token=token,
                        openai_client=openai_client,
                        learning_state=learning_state,
                        scan_days=regen_cfg["scan_days"],
                        score_threshold=regen_cfg["score_threshold"],
                    )
                    if new_post:
                        logger.info("Regenerated post #%s → #%s", post.github_issue_number, new_post.github_issue_number)

            learning_state.save(learning_state_path)

        # Auto-archive stale unpublished drafts after 7 days.
        if (
            post.status not in (PostStatus.PUBLISHED, PostStatus.ARCHIVED, PostStatus.ABANDONED)
            and any(event_key == "stale_unpublished_7d" for event_key, _ in implicit_feedback)
        ):
            update_issue_status(repo, token, post.github_issue_number, PostStatus.ARCHIVED)
            post.status = PostStatus.ARCHIVED
            logger.info("Auto-archived stale unpublished draft: %s", post.id)

        # --- Pass 2: quantitative analytics (published posts only) ---
        if post.status != PostStatus.PUBLISHED:
            continue

        analytics = fetch_issue_analytics(repo, token, post.github_issue_number, post.id)

        if analytics is None:
            # No analytics yet — prompt the user
            print(get_analytics_request_message(post, post.github_issue_number, repo))
            continue

        # Update learning state with quantitative data (feedback already applied above)
        learning_state = update_learning_state(learning_state, post, analytics)
        learning_state.save(learning_state_path)

        # Record experiment results
        if post.experiment_id and post.experiment_variant:
            for exp in experiments.experiments:
                if exp.id == post.experiment_id:
                    experiments.record_result(
                        exp,
                        post.id,
                        post.experiment_variant,
                        analytics.engagement_score,
                    )
                    break

        # Mark analytics as collected on the issue
        add_analytics_comment(repo, token, post.github_issue_number, analytics)
        update_issue_status(repo, token, post.github_issue_number, PostStatus.PUBLISHED)

        logger.info(
            "Analytics processed for post %s (score=%.1f, rate=%.2f%%)",
            post.id,
            analytics.engagement_score,
            analytics.engagement_rate,
        )


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description="GitHub Commit → Social Post Agent",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Scan commits and generate posts (dry run)
  python -m src.agent scan --repo owner/repo --dry-run

  # Scan and create GitHub Issues
  python -m src.agent scan --repo owner/repo

  # Pause generation automatically if draft backlog is high
  python -m src.agent scan --repo owner/repo --max-open-unpublished 8 --max-stale-unpublished 3

  # Collect analytics for published posts (posts provided via stdin JSON)
  python -m src.agent analytics --repo owner/repo --posts posts.json

  # Show experiment summary
  python -m src.agent experiments

  # Show learning state summary (feedback, ratings, not-published reasons)
  python -m src.agent feedback --summary

  # Run weekly self-improvement analysis (writes SELF_IMPROVEMENT.md)
  python -m src.agent self-improve --repo owner/repo --apply

  # Learn from screenshot-only benchmark issues
  python -m src.agent screenshot-learn --repo owner/repo
        """,
    )

    subparsers = parser.add_subparsers(dest="command", required=True)

    # scan command
    scan_parser = subparsers.add_parser("scan", help="Scan commits and generate posts")
    repo_group = scan_parser.add_mutually_exclusive_group(required=True)
    repo_group.add_argument("--repo", help="GitHub repo (owner/repo)")
    repo_group.add_argument("--username", help="GitHub username — scan ALL repos for this user")
    repo_group.add_argument("--repos", nargs="+", help="Explicit list of repos to scan (e.g. owner/repo1 owner/repo2)")
    scan_parser.add_argument(
        "--issue-repo",
        help="Repo where social-post Issues are created (defaults to --repo or first --repos entry)",
    )
    scan_parser.add_argument("--branch", default="main", help="Branch to scan")
    scan_parser.add_argument("--since", help="ISO 8601 date (e.g. 2024-01-01T00:00:00Z)")
    scan_parser.add_argument("--max-posts", type=int, default=10, help="Max posts per run")
    scan_parser.add_argument("--dry-run", action="store_true", help="Print posts, don't create issues")
    scan_parser.add_argument("--threshold", type=float, default=SCORE_THRESHOLD, help="Min score threshold")
    scan_parser.add_argument(
        "--disable-backlog-throttle",
        action="store_true",
        help="Disable backlog throttle and always generate drafts",
    )
    scan_parser.add_argument(
        "--max-open-unpublished",
        type=int,
        default=DEFAULT_MAX_OPEN_UNPUBLISHED,
        help="Backlog throttle limit for open unpublished draft issues",
    )
    scan_parser.add_argument(
        "--max-stale-unpublished",
        type=int,
        default=DEFAULT_MAX_STALE_UNPUBLISHED,
        help="Backlog throttle limit for stale unpublished draft issues",
    )
    scan_parser.add_argument(
        "--stale-days",
        type=int,
        default=DEFAULT_STALE_DAYS,
        help="Issue age threshold in days for stale backlog detection",
    )
    scan_parser.add_argument(
        "--quality-threshold",
        type=float,
        default=QUALITY_GATE_DEFAULT_THRESHOLD,
        help="Minimum post quality score to accept (0-100)",
    )
    scan_parser.add_argument(
        "--max-rewrites",
        type=int,
        default=QUALITY_GATE_DEFAULT_MAX_REWRITES,
        help="Maximum rewrite attempts when quality is below threshold",
    )
    scan_parser.add_argument(
        "--variations",
        type=int,
        default=3,
        help="Number of post variations per commit (different hook patterns, default 3)",
    )

    # analytics command
    analytics_parser = subparsers.add_parser("analytics", help="Collect analytics for published posts")
    analytics_parser.add_argument("--repo", required=True)
    analytics_parser.add_argument("--posts", help="JSON file containing list of Post objects")

    # experiments command
    subparsers.add_parser("experiments", help="Show experiment summary")

    # feedback command
    feedback_parser = subparsers.add_parser(
        "feedback",
        help="Show feedback summary from the learning state",
    )
    feedback_parser.add_argument(
        "--summary",
        action="store_true",
        help="Print a summary of collected feedback and learning signals",
    )
    feedback_parser.add_argument(
        "--state",
        default=DEFAULT_LEARNING_STATE_PATH,
        help="Path to the learning state JSON file",
    )

    # metrics command
    metrics_parser = subparsers.add_parser(
        "metrics",
        help="Generate METRICS.md dashboard and sync dashboard section in README.md",
    )
    metrics_parser.add_argument(
        "--output",
        default="METRICS.md",
        help="Output file path (default: METRICS.md)",
    )
    metrics_parser.add_argument(
        "--state",
        default=DEFAULT_LEARNING_STATE_PATH,
        help="Path to the learning state JSON file",
    )
    metrics_parser.add_argument(
        "--experiments",
        default=DEFAULT_EXPERIMENTS_PATH,
        help="Path to the experiments JSON file",
    )
    metrics_parser.add_argument(
        "--screenshot-state",
        default=DEFAULT_SCREENSHOT_STATE_PATH,
        help="Path to screenshot-learning state JSON file",
    )
    metrics_parser.add_argument(
        "--readme",
        default="README.md",
        help="README path containing metrics markers for auto-sync",
    )
    metrics_parser.add_argument(
        "--no-readme-sync",
        action="store_true",
        help="Do not sync metrics dashboard block in README",
    )

    # backfill-feedback command
    backfill_parser = subparsers.add_parser(
        "backfill-feedback",
        help="Post a minimal feedback request comment on all open social-post issues that don't have one yet",
    )
    backfill_parser.add_argument("--repo", required=True, help="GitHub repo (owner/repo)")
    backfill_parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print which issues would receive a comment without actually posting",
    )

    # linkedin-poll command
    linkedin_parser = subparsers.add_parser(
        "linkedin-poll",
        help="Poll LinkedIn API for post engagement metrics and follower count",
    )
    linkedin_parser.add_argument(
        "--max-posts",
        type=int,
        default=10,
        help="Maximum number of recent posts to fetch engagement for (default: 10)",
    )
    linkedin_parser.add_argument(
        "--output",
        default="linkedin_metrics.json",
        help="Path to write the snapshot history (default: linkedin_metrics.json)",
    )

    # self-improve command
    improve_parser = subparsers.add_parser(
        "self-improve",
        help="Analyze backlog + feedback signals and produce weekly tuning recommendations",
    )
    improve_parser.add_argument("--repo", required=True, help="GitHub repo (owner/repo)")
    improve_parser.add_argument(
        "--state",
        default=DEFAULT_LEARNING_STATE_PATH,
        help="Path to the learning state JSON file",
    )
    improve_parser.add_argument(
        "--config",
        default="config.yaml",
        help="Path to config YAML for automatic tuning",
    )
    improve_parser.add_argument(
        "--output",
        default="SELF_IMPROVEMENT.md",
        help="Output markdown report path (default: SELF_IMPROVEMENT.md)",
    )
    improve_parser.add_argument(
        "--apply",
        action="store_true",
        help="Apply safe tuning adjustments to the config file",
    )

    # screenshot-learn command
    screenshot_parser = subparsers.add_parser(
        "screenshot-learn",
        help="Learn from screenshot-only LinkedIn benchmark issues",
    )
    screenshot_parser.add_argument("--repo", required=True, help="GitHub repo (owner/repo)")
    screenshot_parser.add_argument(
        "--state",
        default=DEFAULT_SCREENSHOT_STATE_PATH,
        help="Path to screenshot-learning state JSON file",
    )
    screenshot_parser.add_argument(
        "--max-issues",
        type=int,
        default=25,
        help="Maximum screenshot issues to process per run",
    )
    screenshot_parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Process and classify without writing state/comments/labels",
    )

    # ingest-linkedin-data command
    ingest_parser = subparsers.add_parser(
        "ingest-linkedin-data",
        help="Parse a LinkedIn Content Export Excel file and produce engagement insights",
    )
    ingest_parser.add_argument("--file", required=True, help="Path to the .xlsx export file")
    ingest_parser.add_argument(
        "--output",
        default="linkedin_insights.json",
        help="Path to write insights JSON (default: linkedin_insights.json)",
    )

    health_parser = subparsers.add_parser(
        "health-check",
        help="Audit system health and report problems",
    )
    health_parser.add_argument(
        "--state",
        default=DEFAULT_LEARNING_STATE_PATH,
        help="Path to learning state JSON file",
    )
    health_parser.add_argument(
        "--repo",
        help="Issue repo to check backlog (default: from config.yaml)",
    )

    regen_parser = subparsers.add_parser(
        "regenerate",
        help="Manually regenerate a rejected post from better source material",
    )
    regen_parser.add_argument("--repo", required=True, help="Issue repo (e.g. nadvolod/magic-social)")
    regen_parser.add_argument("--issue", type=int, required=True, help="GitHub issue number to regenerate")
    regen_parser.add_argument(
        "--feedback",
        help="Feedback to address (overrides issue feedback)",
    )

    learn_parser = subparsers.add_parser(
        "weekly-learn",
        help="Run weekly learning cycle — synthesize feedback, update prompts, generate report",
    )
    learn_parser.add_argument("--repo", required=True, help="Issue repo")
    learn_parser.add_argument(
        "--state", default=DEFAULT_LEARNING_STATE_PATH,
        help="Path to learning state JSON",
    )
    learn_parser.add_argument(
        "--patches", default="prompt_patches.json",
        help="Path to prompt patches JSON",
    )
    learn_parser.add_argument(
        "--output", default="WEEKLY_REPORT.md",
        help="Path to write weekly report",
    )

    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )

    token = os.environ.get("GITHUB_TOKEN")
    if args.command not in ("experiments", "feedback", "metrics", "linkedin-poll", "health-check") and not token:
        print("Error: GITHUB_TOKEN environment variable is required", file=sys.stderr)
        sys.exit(1)

    if args.command == "scan":
        if not (0 <= args.quality_threshold <= 100):
            print("Error: --quality-threshold must be between 0 and 100", file=sys.stderr)
            sys.exit(1)
        if args.max_rewrites < 0:
            print("Error: --max-rewrites must be a non-negative integer", file=sys.stderr)
            sys.exit(1)
        posts = run_scan(
            repo=args.repo,
            token=token,
            since=args.since,
            branch=args.branch,
            max_posts=args.max_posts,
            dry_run=args.dry_run,
            username=args.username,
            repos=getattr(args, "repos", None),
            issue_repo=getattr(args, "issue_repo", None),
            threshold=args.threshold,
            backlog_throttle_enabled=not args.disable_backlog_throttle,
            max_open_unpublished=args.max_open_unpublished,
            max_stale_unpublished=args.max_stale_unpublished,
            stale_days=args.stale_days,
            quality_threshold=args.quality_threshold,
            max_rewrites=args.max_rewrites,
            variations_per_commit=args.variations,
        )
        print(f"\n✅ Generated {len(posts)} post(s).")

    elif args.command == "analytics":
        import json as _json  # noqa: PLC0415
        posts = []
        if args.posts:
            with open(args.posts) as f:
                posts_data = _json.load(f)
            from .models import Post as _Post  # noqa: PLC0415
            posts = [_Post.from_dict(p) for p in posts_data]
        else:
            posts = load_posts_from_issues(args.repo, token, state="all")
            logger.info("Loaded %d posts from GitHub issues for analytics", len(posts))
        run_analytics_collection(repo=args.repo, token=token, posts=posts)

    elif args.command == "experiments":
        manager = ExperimentManager()
        print(manager.summary())

    elif args.command == "feedback":
        _print_feedback_summary(getattr(args, "state", DEFAULT_LEARNING_STATE_PATH))

    elif args.command == "metrics":
        output = generate_metrics_report(
            learning_state_path=getattr(args, "state", DEFAULT_LEARNING_STATE_PATH),
            experiments_path=getattr(args, "experiments", DEFAULT_EXPERIMENTS_PATH),
            screenshot_state_path=getattr(args, "screenshot_state", DEFAULT_SCREENSHOT_STATE_PATH),
        )
        out_file = getattr(args, "output", "METRICS.md")
        with open(out_file, "w", encoding="utf-8") as f:
            f.write(output)
        print(f"✅ METRICS.md written to {out_file}")
        if not getattr(args, "no_readme_sync", False):
            readme_file = getattr(args, "readme", "README.md")
            synced = update_readme_metrics_section(readme_file, output)
            if synced:
                print(f"✅ README metrics dashboard synced in {readme_file}")
            else:
                print(
                    f"⚠️ README metrics markers not found in {readme_file}. "
                    f"Add {README_METRICS_START} ... {README_METRICS_END} to enable sync."
                )

    elif args.command == "backfill-feedback":
        count = backfill_feedback_comments(
            repo=args.repo,
            token=token,
            dry_run=args.dry_run,
        )
        verb = "Would comment on" if args.dry_run else "Commented on"
        print(f"\n✅ {verb} {count} issue(s).")

    elif args.command == "linkedin-poll":
        linkedin_token = os.environ.get("LINKEDIN_ACCESS_TOKEN")
        if not linkedin_token:
            print(
                "Error: LINKEDIN_ACCESS_TOKEN environment variable is required.\n"
                "Set it to your LinkedIn OAuth 2.0 access token.\n"
                "See README.md for setup instructions.",
                file=sys.stderr,
            )
            sys.exit(1)
        run_linkedin_poll(
            access_token=linkedin_token,
            max_posts=args.max_posts,
            output=args.output,
        )

    elif args.command == "self-improve":
        changes, ctx = run_self_improvement_cycle(
            repo=args.repo,
            token=token,
            learning_state_path=args.state,
            config_path=args.config,
            report_output=args.output,
            apply=args.apply,
        )
        print("\n🛠 Self-Improvement Summary")
        print("=" * 50)
        print(f"Social issues:         {ctx.total_social_issues}")
        print(f"Open unpublished:      {ctx.open_unpublished}")
        print(f"Stale unpublished 7d:  {ctx.stale_unpublished_7d}")
        print(f"Unreviewed 72h:        {ctx.old_unreviewed_72h}")
        if changes:
            print("\nApplied config changes:")
            for change in changes:
                print(f"  - {change}")
        else:
            print("\nNo config changes applied.")
        print(f"\nReport written to: {args.output}")

    elif args.command == "screenshot-learn":
        openai_client = _get_openai_client()
        if openai_client is None:
            print("Error: OPENAI_API_KEY is required for screenshot learning.", file=sys.stderr)
            sys.exit(1)
        web_token = os.environ.get("GH_WEB_TOKEN") or os.environ.get("GH_PAT")
        learned = run_screenshot_learning_cycle(
            repo=args.repo,
            token=token,
            state_path=args.state,
            max_issues=args.max_issues,
            dry_run=args.dry_run,
            openai_client=openai_client,
            web_token=web_token,
        )
        print(f"\n✅ Screenshot issues learned: {len(learned)}")
        for ex in learned[:10]:
            print(
                f"  - #{ex.issue_number}: {ex.classification} "
                f"(score={ex.engagement_score:.1f}, p={ex.percentile * 100:.1f}%)"
            )

    elif args.command == "ingest-linkedin-data":
        from .linkedin_data import parse_linkedin_export, analyze_linkedin_data  # noqa: PLC0415

        records = parse_linkedin_export(args.file)
        insights = analyze_linkedin_data(records)
        insights.save(args.output)
        print(f"\n✅ Ingested {insights.total_posts} LinkedIn posts → {args.output}")
        if insights.top_posts:
            print(f"  Top engagement score: {insights.top_posts[0]['score']:.1f}")
        if insights.optimal_length_range != (800, 1500):
            lo, hi = insights.optimal_length_range
            print(f"  Optimal length: {lo}-{hi} chars")
        if insights.engagement_by_day_of_week:
            best_day = max(insights.engagement_by_day_of_week, key=insights.engagement_by_day_of_week.get)  # type: ignore[arg-type]
            print(f"  Best day: {best_day}")

    elif args.command == "health-check":
        problems = run_health_check(
            learning_state_path=args.state,
            token=token,
            repo=args.repo,
        )
        if problems:
            print(f"\n{'=' * 50}")
            print(f"HEALTH CHECK: {len(problems)} problem(s) found")
            print(f"{'=' * 50}")
            for i, problem in enumerate(problems, 1):
                print(f"\n  {i}. {problem}")
            print()
            sys.exit(1)
        else:
            print("\n✅ Health check passed — all systems operational.")
            sys.exit(0)

    elif args.command == "regenerate":
        from .github_storage import load_posts_from_issues as _load  # noqa: PLC0415

        posts = _load(args.repo, token, state="all")
        target = [p for p in posts if p.github_issue_number == args.issue]
        if not target:
            print(f"Error: Issue #{args.issue} not found or not a social-post issue.", file=sys.stderr)
            sys.exit(1)

        post = target[0]
        feedback_text = args.feedback or "manual regeneration requested"
        feedback = PostFeedback(
            post_id=post.id,
            published=False,
            not_published_reason="needs_rewrite",
            improvement_notes=feedback_text,
        )

        openai_client = _get_openai_client()
        learning_state = LearningState.load(DEFAULT_LEARNING_STATE_PATH)
        source_repos = _load_source_repos()

        new_post = regenerate_from_feedback(
            rejected_post=post,
            feedback=feedback,
            source_repos=source_repos,
            issue_repo=args.repo,
            token=token,
            openai_client=openai_client,
            learning_state=learning_state,
        )
        learning_state.save(DEFAULT_LEARNING_STATE_PATH)

        if new_post:
            print(f"\n✅ Regenerated: #{args.issue} → #{new_post.github_issue_number}")
        else:
            print(f"\n❌ Could not regenerate #{args.issue} — no suitable material found.")
            sys.exit(1)

    elif args.command == "weekly-learn":
        from .weekly_learner import run_weekly_learning_cycle  # noqa: PLC0415
        report = run_weekly_learning_cycle(
            repo=args.repo,
            token=token,
            learning_state_path=args.state,
            patches_path=args.patches,
            report_output=args.output,
        )
        print(f"\n✅ Weekly learning cycle complete.")
        print(f"   Report: {args.output}")
        print(f"   Patches: {args.patches}")


def run_health_check(
    learning_state_path: str = DEFAULT_LEARNING_STATE_PATH,
    token: Optional[str] = None,
    repo: Optional[str] = None,
) -> list[str]:
    """
    Audit system components and return a list of problems found.

    Returns an empty list if everything is healthy.
    """
    from .linkedin_api import load_latest_snapshot  # noqa: PLC0415

    state = LearningState.load(learning_state_path)
    problems: list[str] = []

    # Check backlog health
    if repo and token:
        try:
            backlog = fetch_social_post_backlog(repo, token)
            if backlog.stale_unpublished >= DEFAULT_MAX_STALE_UNPUBLISHED:
                problems.append(
                    f"BACKLOG THROTTLE ACTIVE: {backlog.stale_unpublished} stale unpublished "
                    f"drafts (limit: {DEFAULT_MAX_STALE_UNPUBLISHED}). "
                    "New post generation is blocked. Archive or review stale issues."
                )
            if backlog.open_unpublished >= DEFAULT_MAX_OPEN_UNPUBLISHED:
                problems.append(
                    f"OPEN BACKLOG HIGH: {backlog.open_unpublished} open unpublished "
                    f"drafts (limit: {DEFAULT_MAX_OPEN_UNPUBLISHED}). "
                    "Review, publish, or archive some drafts."
                )
        except Exception as exc:  # noqa: BLE001
            problems.append(f"BACKLOG CHECK FAILED: {exc}")

    # Check guardrail status
    threshold, max_posts = apply_learning_guardrails(state, SCORE_THRESHOLD, 10)
    if threshold > SCORE_THRESHOLD or max_posts < 10:
        problems.append(
            f"GUARDRAIL ACTIVE: threshold raised to {threshold:.1f} (base: {SCORE_THRESHOLD}), "
            f"max_posts reduced to {max_posts}. "
            "Historical bad-practice signal is still influencing generation."
        )

    # Check archived bad-batch signals
    archived = state.archived_not_published_reasons or {}
    for reason, count in archived.items():
        if reason.startswith(HISTORICAL_BAD_BATCH_REASON_PREFIX):
            problems.append(
                f"ARCHIVED BAD BATCH: '{reason}' with count={count}. "
                "This signal is archived and decaying over time."
            )

    # Check LinkedIn API
    linkedin = load_latest_snapshot("linkedin_metrics.json")
    if linkedin:
        if linkedin.follower_count == 0 and not linkedin.post_metrics:
            problems.append(
                "LINKEDIN NOT CONNECTED: Daily polls return 0 followers and no posts. "
                "Check that LINKEDIN_ACCESS_TOKEN is set and not expired."
            )
    else:
        problems.append(
            "LINKEDIN NEVER POLLED: No linkedin_metrics.json found. "
            "Run `python -m src.agent linkedin-poll` to start collecting data."
        )

    # Check learning loop health
    if state.total_posts_analyzed == 0:
        problems.append(
            "LEARNING LOOP INACTIVE: No posts have quantitative analytics. "
            "Publish posts and enter analytics data to start the feedback loop."
        )

    # Check scoring weights (all at 1.0 = no learning)
    all_default = all(w == 1.0 for w in state.scoring_weights.values())
    if all_default and state.total_feedback_received > 10:
        problems.append(
            "WEIGHTS UNCHANGED: All scoring weights are at 1.0 despite "
            f"{state.total_feedback_received} feedback entries. "
            "The system has not learned from any published post analytics."
        )

    # Check good-social-posts calibration
    good_posts_dir = Path("good-social-posts")
    good_posts_count = len(list(good_posts_dir.glob("*.md"))) if good_posts_dir.exists() else 0
    if good_posts_count < 3:
        problems.append(
            f"LOW CALIBRATION DATA: Only {good_posts_count} example(s) in good-social-posts/. "
            "Add 3-5 high-performing LinkedIn posts for better generation quality."
        )

    # Check OpenAI key
    if not os.environ.get("OPENAI_API_KEY"):
        problems.append(
            "OPENAI_API_KEY NOT SET: Post generation requires an OpenAI API key."
        )

    return problems


def backfill_feedback_comments(repo: str, token: str, dry_run: bool = False) -> int:
    """
    Find all open GitHub Issues with the 'social-post' label and post a minimal
    feedback request comment on any that don't already have one.

    Returns the number of issues that received (or would receive) a comment.
    """
    import requests as _requests  # noqa: PLC0415

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    # Fetch all open issues with the social-post label
    issues: list[dict] = []
    page = 1
    while True:
        url = f"https://api.github.com/repos/{repo}/issues"
        resp = _requests.get(
            url,
            headers=headers,
            params={"state": "open", "labels": "social-post", "per_page": 100, "page": page},
            timeout=30,
        )
        resp.raise_for_status()
        batch = resp.json()
        if not batch:
            break
        issues.extend(batch)
        page += 1

    logger.info("Found %d open social-post issues in %s", len(issues), repo)

    # Minimal feedback template — as short as possible while still being parseable
    feedback_template = (
        "## Quick Feedback\n\n"
        "Fastest options:\n\n"
        "- React to the issue: 👍 good, 👎 bad, 🚀 published\n"
        "- Or comment one word: `publish`, `rewrite`, `skip`, `too long`, `not relevant`, `weak hook`\n\n"
        "Optional full template:\n\n"
        "```\n"
        "## Post Feedback\n\n"
        "- Verdict: ✅ published  OR  ❌ skipped\n"
        "- Reason: quality / style / not relevant / too long / too technical / other\n"
        "- Improve: <short text>\n"
        "- Rating: 1-5\n"
        "```\n\n"
        "Or use the detailed format:\n\n"
        "```\n"
        "## Post Feedback\n\n"
        "- Published: yes / no\n"
        "- If not published, why: quality / style / not relevant / too long / too technical / other\n"
        "- What would make it better: \n"
        "- Rating (1-5): \n"
        "```\n\n"
        "_Your feedback is used to improve future post generation. "
        "Every rating helps — even a simple 1–5 number is valuable._"
    )

    count = 0
    for issue in issues:
        issue_number = issue["number"]
        title = issue.get("title", "")

        # Check if a feedback comment already exists
        comments_url = f"https://api.github.com/repos/{repo}/issues/{issue_number}/comments"
        comments_resp = _requests.get(comments_url, headers=headers, params={"per_page": 100}, timeout=30)
        comments_resp.raise_for_status()
        existing_comments = comments_resp.json()

        already_has_feedback = any(
            "Post Feedback" in c.get("body", "") or "Quick Feedback" in c.get("body", "")
            for c in existing_comments
        )
        # Also check the issue body itself (new issues already have quick feedback section)
        if "Post Feedback" in issue.get("body", "") or "Quick Mobile Feedback" in issue.get("body", ""):
            already_has_feedback = True

        if already_has_feedback:
            logger.debug("Issue #%d already has a feedback section — skipping", issue_number)
            continue

        if dry_run:
            print(f"  [dry-run] Would post feedback request on #{issue_number}: {title[:70]}")
        else:
            post_resp = _requests.post(
                comments_url,
                headers=headers,
                json={"body": feedback_template},
                timeout=30,
            )
            post_resp.raise_for_status()
            print(f"  ✓ Posted feedback request on #{issue_number}: {title[:70]}")
            logger.info("Posted feedback comment on issue #%d", issue_number)

        count += 1

    return count


def run_linkedin_poll(
    access_token: str,
    max_posts: int = 10,
    output: str = "linkedin_metrics.json",
) -> None:
    """
    Poll the LinkedIn API, save the snapshot, and print a summary.
    """
    from .linkedin_api import poll_linkedin, save_snapshot  # noqa: PLC0415

    snapshot = poll_linkedin(access_token, max_posts=max_posts)
    save_snapshot(snapshot, path=output)

    print("\n📊 LinkedIn Metrics Snapshot")
    print("=" * 50)
    print(f"Recorded at:         {snapshot.recorded_at[:19].replace('T', ' ')} UTC")
    print(f"Followers/connections: {snapshot.follower_count:,}")
    print(f"Posts fetched:       {len(snapshot.post_metrics)}")
    if snapshot.post_metrics:
        print("\nPost engagement:")
        for pm in snapshot.post_metrics:
            print(
                f"  {pm.created_at[:10]}  likes={pm.likes}  comments={pm.comments}  "
                f"shares={pm.shares}  impressions={pm.impressions}  "
                f"score={pm.engagement_score:.0f}"
            )
    print(f"\nSaved to: {output}")


def generate_metrics_report(
    learning_state_path: str = DEFAULT_LEARNING_STATE_PATH,
    experiments_path: str = DEFAULT_EXPERIMENTS_PATH,
    linkedin_metrics_path: str = "linkedin_metrics.json",
    screenshot_state_path: str = DEFAULT_SCREENSHOT_STATE_PATH,
) -> str:
    """
    Generate a Markdown metrics dashboard from the current learning state and experiments.

    Returns the full Markdown string — caller decides where to write it.
    """
    from .linkedin_api import load_latest_snapshot  # noqa: PLC0415

    state = LearningState.load(learning_state_path)
    experiments = ExperimentManager(experiments_path)
    linkedin = load_latest_snapshot(linkedin_metrics_path)
    screenshot_state = ScreenshotLearningState.load(screenshot_state_path)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = []

    # ------------------------------------------------------------------ header
    lines += [
        "# 📊 magic-social — Metrics Dashboard",
        "",
        f"> Last updated: **{now}**  ",
        "> Auto-generated by `python -m src.agent metrics`",
        "",
        "---",
        "",
    ]

    # ------------------------------------------------- system health (new)
    linkedin_connected = bool(
        linkedin and (linkedin.follower_count > 0 or linkedin.post_metrics)
    )
    any_weight_changed = any(w != 1.0 for w in state.scoring_weights.values())
    any_experiment_running = any(
        (e.status.value if hasattr(e.status, "value") else e.status) == "running"
        for e in experiments.experiments
    )
    learning_active = any_weight_changed or any_experiment_running

    # Detect generation stall: check not_published_reasons for stale signals
    stale_count = state.not_published_reasons.get("stale_unpublished_7d", 0)
    archived_bad_batch = sum(
        int(v) for k, v in (state.archived_not_published_reasons or {}).items()
        if k.startswith(HISTORICAL_BAD_BATCH_REASON_PREFIX)
    )
    generation_stalled = stale_count >= DEFAULT_MAX_STALE_UNPUBLISHED
    stall_reasons = []
    if generation_stalled:
        stall_reasons.append(f"backlog throttle ({stale_count} stale drafts)")
    if archived_bad_batch > 0:
        stall_reasons.append(f"historical bad-batch archived ({archived_bad_batch} posts, decaying)")

    gen_status = "STALLED" if generation_stalled else "ACTIVE"
    gen_detail = " — " + ", ".join(stall_reasons) if stall_reasons else ""

    lines += [
        "## System Health",
        "",
        "| Component | Status |",
        "|-----------|--------|",
        f"| Post generation | **{gen_status}**{gen_detail} |",
        f"| LinkedIn API | **{'CONNECTED' if linkedin_connected else 'NOT CONNECTED'}**"
        f"{' — set up LINKEDIN_ACCESS_TOKEN' if not linkedin_connected else ''} |",
        f"| Learning loop | **{'ACTIVE' if learning_active else 'WAITING'}**"
        f"{' — publish a generated post and enter analytics to activate' if not learning_active else ''} |",
        f"| A/B experiments | **{'RUNNING' if any_experiment_running else 'QUEUED'}**"
        f"{' — starts after 3+ generated posts are published from this system' if not any_experiment_running else ''} |",
        "",
        "---",
        "",
    ]

    # ------------------------------------------------- high-level scorecard
    explicit_rating_str = (
        f"{state.explicit_average_rating:.1f} / 5"
        if state.explicit_ratings_received > 0
        else "n/a (no explicit ratings yet)"
    )
    avg_rating_str = f"{state.average_rating:.1f} / 5" if state.total_ratings_received > 0 else "n/a (no ratings yet)"
    total_posts = state.total_posts_analyzed
    total_feedback = state.total_feedback_received

    lines += [
        "## 🏆 Current Scorecard",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Posts analyzed | {total_posts} |",
        f"| Feedback received | {total_feedback} |",
        f"| Average post rating (explicit) | {explicit_rating_str} |",
        f"| Average post rating (all incl. implicit) | {avg_rating_str} |",
        f"| Best performing posts (rolling 20) | {len(state.best_performing_posts)} |",
        f"| Screenshot examples analyzed | {len(screenshot_state.examples)} |",
        f"| Screenshot top 10% | {screenshot_state.top_10_count} |",
    ]

    if linkedin_connected:
        lines += [
            f"| LinkedIn followers/connections | {linkedin.follower_count:,} |",
            f"| LinkedIn posts tracked | {len(linkedin.post_metrics)} |",
            f"| LinkedIn metrics last updated | {linkedin.recorded_at[:10]} |",
        ]
    else:
        lines.append("| LinkedIn metrics | NOT CONNECTED — run `linkedin-poll` after setting `LINKEDIN_ACCESS_TOKEN` |")

    lines += [
        "",
        "> **Goal:** average rating ≥ 4.0 / 5, engagement score ≥ 100 per post",
        "",
        "---",
        "",
    ]

    # ------------------------------------------------- direction / momentum
    lines += [
        "## 🧭 Direction",
        "",
        "We are optimizing for **LinkedIn posts that Nikolay actually publishes**.",
        "",
        "The two key signals that drive every decision:",
        "",
        "1. **Qualitative** — Did you publish it? If not, why? Rating 1–5.",
        "2. **Quantitative** — Saves, comments, reposts, impressions (entered after 48 h).",
        "",
        "Current blockers (from `not_published_reasons`):",
        "",
    ]

    if state.not_published_reasons:
        sorted_reasons = sorted(state.not_published_reasons.items(), key=lambda x: -x[1])
        for reason, count in sorted_reasons:
            bar = "█" * count
            lines.append(f"- **{reason}** — {count}× {bar}")
    else:
        lines.append("- _No feedback collected yet. Use issue reactions (👍/👎/🚀) or a quick comment._")

    lines += ["", "---", ""]

    # ------------------------------------------------- hook pattern leaderboard
    lines += [
        "## 🪝 Hook Pattern Leaderboard",
        "",
        "Ranked by average engagement score (saves×4 + reposts×3 + comments×3 + reactions×1 + ctr×2).",
        "",
        "| Rank | Hook Pattern | Avg Score | Posts (n) | Trend |",
        "|------|-------------|-----------|-----------|-------|",
    ]

    if state.hook_pattern_scores:
        ranked = sorted(
            state.hook_pattern_scores.items(),
            key=lambda kv: kv[1]["total_score"] / max(kv[1]["count"], 1),
            reverse=True,
        )
        for i, (pattern, data) in enumerate(ranked, 1):
            avg = data["total_score"] / max(data["count"], 1)
            medal = ["🥇", "🥈", "🥉"][i - 1] if i <= 3 else f"#{i}"
            # Trend is rank-based (top half vs bottom half), not time-series data
            trend = "↑" if i <= len(ranked) / 2 else "↓"
            lines.append(f"| {medal} | `{pattern}` | {avg:.1f} | {data['count']} | {trend} |")
    else:
        lines.append("| — | _No data yet_ | — | 0 | — |")

    if state.hook_pattern_scores:
        best_hook = max(
            state.hook_pattern_scores,
            key=lambda k: state.hook_pattern_scores[k]["total_score"] / max(state.hook_pattern_scores[k]["count"], 1),
        )
        best_hook_label = f"`{best_hook}`"
    else:
        best_hook_label = "_learning…_"

    lines += [
        "",
        f"> **Current best hook:** {best_hook_label}",
        "",
        "---",
        "",
    ]

    # ------------------------------------------------- topic leaderboard
    lines += [
        "## 🏷 Topic Leaderboard",
        "",
        "| Rank | Topic | Avg Score | Posts (n) |",
        "|------|-------|-----------|-----------|",
    ]

    if state.topic_scores:
        ranked_topics = sorted(
            state.topic_scores.items(),
            key=lambda kv: kv[1]["total_score"] / max(kv[1]["count"], 1),
            reverse=True,
        )
        for i, (topic, data) in enumerate(ranked_topics, 1):
            avg = data["total_score"] / max(data["count"], 1)
            lines.append(f"| #{i} | `{topic}` | {avg:.1f} | {data['count']} |")
    else:
        lines.append("| — | _No data yet_ | — | 0 |")

    lines += ["", "---", ""]

    # ------------------------------------------------- scoring weights
    lines += [
        "## ⚖️ Scoring Weights (Learning Loop)",
        "",
        "These weights are automatically adjusted: dimensions that correlate with high engagement get a boost.",
        "",
        "| Dimension | Weight | Direction |",
        "|-----------|--------|-----------|",
    ]
    for dim, weight in state.scoring_weights.items():
        direction = "↑" if weight > 1.0 else ("↓" if weight < 1.0 else "—")
        bar_len = int(weight * 10)
        bar = "█" * bar_len
        lines.append(f"| {dim} | {weight:.3f} {bar} | {direction} |")

    lines += ["", "---", ""]

    # ------------------------------------------------- experiments
    lines += [
        "## 🧪 Experiment Tracker",
        "",
        "Sequential A/B experiments, each running until ≥3 posts per variant.",
        "",
        "| # | Variable | Variants | Hypothesis | Status | Winner |",
        "|---|----------|----------|------------|--------|--------|",
    ]

    completed_vars = {
        e.variable.value if hasattr(e.variable, "value") else e.variable
        for e in experiments.experiments
    }
    active_exp = experiments.get_active_experiment()

    for i, plan in enumerate(EXPERIMENT_PLAN, 1):
        var = plan["variable"].value if hasattr(plan["variable"], "value") else str(plan["variable"])
        variants_str = ", ".join(f"`{v}`" for v in plan["variants"])
        hypothesis = plan["hypothesis"]

        # Find matching experiment result
        matching = [
            e for e in experiments.experiments
            if (e.variable.value if hasattr(e.variable, "value") else e.variable) == var
        ]
        if matching:
            exp = matching[-1]
            status_icon = {"running": "🔄 Running", "concluded": "✅ Done", "paused": "⏸ Paused"}.get(
                exp.status.value if hasattr(exp.status, "value") else exp.status, "❓"
            )
            winner = f"**{exp.winner}**" if exp.winner else "—"
        elif active_exp is None and var not in completed_vars:
            status_icon = "⏳ Next up"
            winner = "—"
        else:
            status_icon = "⬜ Queued"
            winner = "—"

        lines.append(f"| {i} | {var} | {variants_str} | {hypothesis} | {status_icon} | {winner} |")

    lines += ["", "---", ""]

    # ------------------------------------------------- screenshot learning
    lines += [
        "## 🖼️ Screenshot Learning",
        "",
        "Benchmark issues labeled `social-screenshot` are AI-read from screenshots only,",
        "classified into top 10% vs bottom 90%, then converted into signal memory.",
        "",
        f"- Screenshots processed: **{len(screenshot_state.examples)}**",
        f"- Top 10% examples: **{screenshot_state.top_10_count}**",
        f"- Bottom 90% examples: **{screenshot_state.bottom_90_count}**",
        "",
    ]
    positives, negatives = build_signal_balance(screenshot_state, top_n=6)
    if positives:
        lines.append("**Winning signals to repeat:**")
        lines.extend(f"- `{p}`" for p in positives)
        lines.append("")
    if negatives:
        lines.append("**Signals to avoid:**")
        lines.extend(f"- `{n}`" for n in negatives)
        lines.append("")
    if not positives and not negatives:
        lines += [
            "_No screenshot signal deltas yet. Open an issue with label `social-screenshot` and upload one screenshot._",
            "",
        ]

    lines += ["---", ""]

    # ------------------------------------------------- qualitative feedback
    implicit_count = sum(
        len(events) for events in state.implicit_feedback_events.values()
    )
    explicit_count = state.total_feedback_received - implicit_count

    lines += [
        "## 💬 Qualitative Feedback",
        "",
        "Parsed from GitHub Issue reactions, quick comments, and `## Post Feedback` templates.",
        "",
        f"- Explicit user feedback: **{explicit_count}** comments, "
        f"**{state.explicit_ratings_received}** ratings, "
        f"avg **{explicit_rating_str}**",
        f"- Implicit signals (automated): **{implicit_count}** "
        "(posts auto-marked after 72h no feedback or 7d stale)",
        f"- Combined total: **{state.total_feedback_received}** feedback entries",
        "",
        "**Improvement themes** (from 'What would make it better?'):",
        "",
        "_Use quick reactions (👍/👎/🚀), mobile format, or a short comment on any post issue to contribute data here._",
        "",
        "### How to Give Feedback",
        "",
        "On any generated GitHub Issue, choose the fastest option:",
        "",
        "- React to the issue: 👍 good draft, 👎 bad draft, 🚀 published",
        "- Add a short comment: `publish`, `rewrite`, `skip`, `too long`, `not relevant`, `weak hook`",
        "",
        "Quick mobile format:",
        "",
        "```",
        "## Post Feedback",
        "",
        "- Verdict: ✅ published  OR  ❌ skipped",
        "- Reason: quality / style / not relevant / too long / too technical / other",
        "- Improve: ",
        "- Rating: 1-5",
        "```",
        "",
        "Optional full template:",
        "",
        "```",
        "## Post Feedback — YYYY-MM-DD",
        "",
        "- Published: yes / no",
        "- If not published, why: quality / style / not relevant / too long / too technical / other",
        "- What would make it better: ",
        "- Rating (1-5): ",
        "```",
        "",
        "Free-text also works (still include `## Post Feedback`):",
        "",
        "```",
        "## Post Feedback",
        "This one felt too generic. Make it sharper and include one concrete number.",
        "```",
        "",
        "---",
        "",
    ]

    # ------------------------------------------------- linkedin metrics
    lines += [
        "## 🔗 LinkedIn Metrics",
        "",
    ]

    if linkedin_connected:
        lines += [
            f"_Data from poll on {linkedin.recorded_at[:10]}_",
            "",
            f"**Followers / connections:** {linkedin.follower_count:,}",
            "",
        ]
        if linkedin.post_metrics:
            lines += [
                "| Date | Likes | Comments | Shares | Impressions | Engagement Score |",
                "|------|-------|----------|--------|-------------|-----------------|",
            ]
            for pm in sorted(linkedin.post_metrics, key=lambda p: p.created_at, reverse=True):
                lines.append(
                    f"| {pm.created_at[:10]} | {pm.likes} | {pm.comments} | "
                    f"{pm.shares} | {pm.impressions} | {pm.engagement_score:.0f} |"
                )
            lines.append("")
        else:
            lines.append("_No post metrics in the latest snapshot._")
            lines.append("")
    else:
        lines += [
            "**NOT CONNECTED** — LinkedIn API is not returning data.",
            "",
            "The daily poll has been running but returning 0 followers and no posts.",
            "This usually means `LINKEDIN_ACCESS_TOKEN` is missing or expired.",
            "",
            "To fix:",
            "1. Create or refresh your LinkedIn OAuth token (see README for setup)",
            "2. Add it as `LINKEDIN_ACCESS_TOKEN` in GitHub Secrets",
            "3. Run `python -m src.agent linkedin-poll` to verify",
            "",
        ]

    lines += ["---", ""]

    # ------------------------------------------------- dynamic action items
    good_posts_dir = Path("good-social-posts")
    good_posts_count = len(list(good_posts_dir.glob("*.md"))) if good_posts_dir.exists() else 0

    action_items: list[str] = []

    if generation_stalled:
        action_items.append(
            "**Unblock post generation** — stale drafts are blocking new posts. "
            "Review/archive old draft issues or run a scan with `--disable-backlog-throttle`"
        )
    if not linkedin_connected:
        action_items.append(
            "**Connect LinkedIn API** — add `LINKEDIN_ACCESS_TOKEN` to GitHub Secrets "
            "to start tracking real engagement data"
        )
    if good_posts_count < 3:
        action_items.append(
            f"**Add more good-post examples** — only {good_posts_count} example(s) in "
            "`good-social-posts/`. Add 3-5 real LinkedIn posts that performed well"
        )
    if total_posts == 0:
        action_items.append(
            "**Publish your first post** — the learning loop, experiments, and weight "
            "adjustments all need at least 1 published post with analytics"
        )
    if state.explicit_ratings_received > 0 and state.explicit_average_rating < 3.0:
        action_items.append(
            "**Review feedback themes** — explicit average rating is below 3.0. "
            "Check recent feedback and update generation prompt or examples"
        )
    if not any_experiment_running and total_posts < 3:
        action_items.append(
            "**Run first A/B experiment** — publish 3+ posts to start testing "
            "which hook patterns drive the most engagement"
        )

    lines += [
        "## 🚀 Action Items",
        "",
    ]
    if action_items:
        lines.append("Prioritized by impact on getting the system producing and improving:\n")
        for i, item in enumerate(action_items, 1):
            lines.append(f"{i}. {item}")
    else:
        lines.append("System is healthy. Keep publishing posts and providing feedback to improve quality.")
    lines += ["", "---", ""]

    # ------------------------------------------------- how to update
    lines += [
        "## 🔁 How to Update This Dashboard",
        "",
        "```bash",
        "# Regenerate METRICS.md from current learning state + experiments",
        "python -m src.agent metrics",
        "",
        "# Post feedback requests on all existing open issues (run once)",
        "python -m src.agent backfill-feedback --repo owner/repo",
        "",
        "# Poll LinkedIn API for post metrics + follower count",
        "python -m src.agent linkedin-poll",
        "",
        "# Learn from screenshot-only benchmark issues",
        "python -m src.agent screenshot-learn --repo owner/repo",
        "",
        "# Collect analytics (updates learning state, then regenerate)",
        "python -m src.agent analytics --repo owner/repo --posts posts.json",
        "python -m src.agent metrics",
        "```",
        "",
        "> **Tip:** The daily LinkedIn poll workflow (`.github/workflows/linkedin-poll.yml`) runs",
        "> automatically and commits updated dashboard files (`linkedin_metrics.json`, `METRICS.md`, `README.md`).",
        "",
    ]

    # ------------------------------------------------- agent performance dashboard
    try:
        from .agents.bar_raiser import BarRaiserState, render_agent_dashboard  # noqa: PLC0415
        bar_state = BarRaiserState.load()
        if bar_state.post_history:
            lines += ["", "---", "", render_agent_dashboard(bar_state), ""]
    except (ImportError, FileNotFoundError):
        pass  # Module or state file not available yet
    except Exception:  # noqa: BLE001
        logger.warning("Failed to render agent dashboard", exc_info=True)

    return "\n".join(lines)


def _print_feedback_summary(learning_state_path: str) -> None:
    """Print a human-readable summary of collected feedback and learning signals."""
    state = LearningState.load(learning_state_path)

    print("\n📊 Feedback & Learning Summary")
    print("=" * 50)
    print(f"Total posts analyzed:    {state.total_posts_analyzed}")
    print(f"Total feedback received: {state.total_feedback_received}")
    avg = f"{state.average_rating:.1f}/5" if state.average_rating > 0 else "n/a"
    print(f"Average post rating:     {avg}")

    if state.not_published_reasons:
        print("\n❌ Reasons posts were NOT published:")
        for reason, count in sorted(state.not_published_reasons.items(), key=lambda x: -x[1]):
            print(f"  • {reason}: {count}")
    else:
        print("\n❌ No 'not published' feedback recorded yet.")

    if state.hook_pattern_scores:
        print("\n🪝 Hook pattern performance (avg engagement score):")
        for pattern, data in sorted(
            state.hook_pattern_scores.items(),
            key=lambda kv: kv[1]["total_score"] / max(kv[1]["count"], 1),
            reverse=True,
        ):
            avg_score = data["total_score"] / max(data["count"], 1)
            print(f"  • {pattern}: {avg_score:.1f} (n={data['count']})")

    if state.topic_scores:
        print("\n🏷  Topic performance (avg engagement score):")
        for topic, data in sorted(
            state.topic_scores.items(),
            key=lambda kv: kv[1]["total_score"] / max(kv[1]["count"], 1),
            reverse=True,
        ):
            avg_score = data["total_score"] / max(data["count"], 1)
            print(f"  • {topic}: {avg_score:.1f} (n={data['count']})")

    print()


if __name__ == "__main__":
    main()
